### ISSUE TITLE
 CMake 3.10 or higher is required.  You are running version 3.7.2

### ISSUE THREAD

**Issue by KVPV** [tostercx/ssocks#6]
CMake 3.10 or higher is required.  You are running version 3.7.2

**Comment by tostercx** [comment]
Yeah, cmake enters the current version as the required by default, should probably run fine on older versions as well.

You can edit https://github.com/tostercx/ssocks/blob/master/CMakeLists.txt#L1 for now and enter `cmake_minimum_required(VERSION 3.7)`. or something.

Tell me if it builds alright, I'll loosen the required version.

**Comment by KVPV** [comment]
I solved the problem by installing CMake of the correct version.
